### ISSUE TITLE
Template injection not working on Symfony 4.2

### ISSUE THREAD

**Issue by KlaasT** [karser/KarserRecaptcha3Bundle#1]
Hi,

thanks for that bundle. I had an issue with Symfony 4.2 when injecting the template.

`$resources[] = 'KarserRecaptcha3Bundle:Form:karser_recaptcha3_widget.html.twig';`

Would give an error 500 with Symfony 4.2. I had to change this to:

`$resources[] = '@KarserRecaptcha3/Form/karser_recaptcha3_widget.html.twig';`

**Comment by karser** [comment]
You probably encountered [this issue](https://mikevanriel.com/2018/02/23/when-your-template-cannot-be-found-in-symfony-4/). I have `templating` installed, that's why I didn't notice this. I'll fix it, thanks.
