### ISSUE TITLE
GET catpcha: HTTP 400

### ISSUE THREAD

**Issue by matyaspeto** [karser/KarserRecaptcha3Bundle#10]
Hi,

I added the bundle to my Symfony 4 app as per description, and now when FOS registration form is loaded,  I have this http 400 error:

GET https://www.google.com/recaptcha/api.js?render=MY SITEKEY&onload=recaptchaCallback_fos_user_registration_form_captcha 400

Do you have any idea, why?

**Comment by karser** [comment]
What does 400 stand for? Validation error? What is the error then?
Is the api.js file loaded or are you getting an error in its response?
There recently was a similar issue - please follow my responses, maybe it'll help https://github.com/karser/KarserRecaptcha3Bundle/issues/9

**Comment by matyaspeto** [comment]
Yea, looks like I requested the keys for v2, not v3 -_- sry and thanks!
