### ISSUE TITLE
Update docs/config for symfony Recipe and symfony 5

### ISSUE THREAD

**Issue by RootProgger** [karser/KarserRecaptcha3Bundle#11]
I have installed this bundle on a fresh SF5 application. 
but the generated config files does not match with your docs.

- config/packages/goggle_recaptcha.yaml instead of config/packages/karser_recaptcha3.yaml
- in .env "GOOGLE_RECAPTCHA_SITE_KEY" and "GOOGLE_RECAPTCHA_SECRET" instead of RECAPTCHA3_KEY=my_site_key
RECAPTCHA3_SECRET=my_secret

is this config obsolet?
karser_recaptcha3:
    site_key: '%env(RECAPTCHA3_KEY)%'
    secret_key: '%env(RECAPTCHA3_SECRET)%'
    score_threshold: 0.5
when yes, why the config-tree has this dependencies?

**Comment by karser** [comment]
You can safely remove `google_recaptcha.yaml` and follow the instructions in readme.

This bundle requires `google/recaptcha` which has flex recipe which creates `config/packages/google_recaptcha.yaml`.

I should probably add it to readme.

**Comment by karser** [comment]
Documented https://github.com/karser/KarserRecaptcha3Bundle/blob/master/README.md#installation
