### ISSUE TITLE
Composer require - Config issue

### ISSUE THREAD

**Issue by bonswouar** [karser/KarserRecaptcha3Bundle#12]
Seems to be a problem with last config changes ?
After executing `composer require karser/karser-recaptcha3-bundle` (and ignoring `google/recaptcha` script) I have the following error :
```
  The child node "site_key" at path "karser_recaptcha3" must be configured.  
```
And then `composer.json` is reverted.

And the weird thing is that even if I preconfigure the `karser_recaptcha3` params I still have the error !

Any idea ?

Using Symfony 4.4, composer 1.9.1, php 7.1.28

**Comment by karser** [comment]
Reproduced this. You should also add environment variables to .env or to .env.local before launching `composer require karser/karser-recaptcha3-bundle` 
```
RECAPTCHA3_KEY=
RECAPTCHA3_SECRET=
```

**Comment by karser** [comment]
Added flex recipe for this bundle https://github.com/symfony/recipes-contrib/pull/822
When it's merged all the configs will be created automatically.

**Comment by karser** [comment]
it's merged. Now the installation with flex is seamless.
