### ISSUE TITLE
List of little issues

### ISSUE THREAD

**Issue by Nek-** [karser/KarserRecaptcha3Bundle#2]
Hello thanks for providing open source a bundle for Recaptcha3, this is really kind. I'm going to try to help with a list of some things that can be improved:

- [x] You should not retrieve `HTTP_CF_CONNECTING_IP` directly. I understand this is on your use case but you probably should have a custom request or an IP resolver. It should not be hardcoded inside the validator
- [x] [enabled](https://github.com/karser/KarserRecaptcha3Bundle/blob/7100d3e94f657352f82352c1ed9cb55771de4832/Form/Recaptcha3Type.php#L46) option of form type is useless (is not used and makes no sense)
- [ ] It should exist a way to add it to other pages than forms (considering this practice highly improve the power of the captcha)
- [x] Unit tests are missing!

**Comment by karser** [comment]
Thank you for the feedback.
- Indeed, there is a chance that IP can be overridden by providing `CF-Connecting-IP` header if you are not using Cloudflare. The IP resolver would work. What do you mean by `custom request`?
- Setting `enabled` to `false` is convenient when it comes to functional and e2e testing.

**Comment by Nek-** [comment]
The Symfony request may be extended to add some custom stuff. (btw there are standards way to [forward ip that are supported by Symfony](https://symfony.com/doc/current/deployment/proxies.html) and may be a better option if also supported by cloudflare, IDK)

The code I linked is useless.

**Comment by karser** [comment]
```
It should exist a way to add it to other pages than forms (considering this practice highly improve the power of the captcha)
```
What do you mean here?
I'm using this bundle [in API methods](https://github.com/karser/KarserRecaptcha3Bundle#how-to-integrate-re-captcha-in-api-method) as well, but not sure what are other cases?

**Comment by Nek-** [comment]
For the last part: https://developers.google.com/recaptcha/docs/v3#placement
