### ISSUE TITLE
symfony/templating is deprecated

### ISSUE THREAD

**Issue by timwsuqld** [karser/KarserRecaptcha3Bundle#22]
https://symfony.com/doc/4.4/templating/PHP.html

`symfony/templating` has been deprecated from 4.3 and will be removed in 5. The solution is to stop depending on `symfony/templating` and just to use Twig. Otherwise using `karser/karser-recaptcha3-bundle` will pull in `symfony/templating` and throw lots of deprecation warnings.

Edit: I'm not sure how necessary this is. It does seem in the 4.4 upgrade instructions we can disable the TwigEngine loader and get rid of the deprecations.

**Comment by karser** [comment]
@timwsuqld  Do you think that's the only change that is required? https://github.com/karser/KarserRecaptcha3Bundle/pull/23
Tests pass even for symfony 3.4

**Comment by timwsuqld** [comment]
I believe so. I couldn't see anywhere you are using the service directly.
