### ISSUE TITLE
SF 5.1 Configurator\ref deprecation in config/services.php

### ISSUE THREAD

**Issue by sabat24** [karser/KarserRecaptcha3Bundle#27]
I noticed that SF made a `Symfony\Component\DependencyInjection\Loader\Configurator\ref` deprecated. 
You should change 

`use function Symfony\Component\DependencyInjection\Loader\Configurator\ref;`
to
`use function \Symfony\Component\DependencyInjection\Loader\Configurator\service;`

and then in your `args` `ref` -> `service`

**Comment by karser** [comment]
Should be fixed in [v0.1.11](https://github.com/karser/KarserRecaptcha3Bundle/releases/tag/v0.1.11)
