### ISSUE TITLE
Get captcha value null on form submit

### ISSUE THREAD

**Issue by darshit261991** [karser/KarserRecaptcha3Bundle#31]
Hi I am getting captcha value null on form submit. 

I can see the input field being set properly, token value is also updating in the input field but still getting captcha value null on form submit.

Thanks

**Comment by karser** [comment]
Is the captcha value being sent in the network tab of development console?
Also, check [the troubleshooting checklist](https://github.com/karser/KarserRecaptcha3Bundle#troubleshooting-checklist)

**Comment by karser** [comment]
Closed by #30

**Comment by karser** [comment]
Closing this issue since no feedback. Feel free to open a new one if the issue still persists.
