### ISSUE TITLE
Symfony 5 : Error: Unknown base64 encoding at char

### ISSUE THREAD

**Issue by Sheitak** [karser/KarserRecaptcha3Bundle#33]
Hello Karser,

I am using your Bundle v3 and followed the installation. I want to integrate the ReCaptcha on a basic contact form,

I install with flex and am on Symfony 5.1, fill in my **ContactType** file as it should, then also write the two JavaScript scripts in my layout,

All that remains is to fill in my secret key and my Captcha key,

Despite all this, my inspector gives me the following error `Error: Unknown base64 encoding at char:`
The submission works, but does not seem to involve the captcha, I think I am not using the bundle completely correctly, would you have an indication for me please ?

I share with you the status of my current code, thank you very much for your work !

Layout.html.twig
```
<script>
const recaptchaCallback_form_captcha = function() {
grecaptcha.execute('******************************', {action: 'landing'}).then(function(token) {
document.getElementById('form_captcha').value = token;
});
};
</script>

<script src="https://www.google.com/recaptcha/api.js?render=******************************&onload=recaptchaCallback_form_captcha" async defer></script>
```
ContactType.php

```
namespace App\Form;

use App\Entity\Contact;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Karser\Recaptcha3Bundle\Form\Recaptcha3Type;
use Karser\Recaptcha3Bundle\Validator\Constraints\Recaptcha3;

class ContactType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('pseudo')
            ->add('email')
            ->add('subject')
            ->add('message', TextareaType::class)
            ->add('captcha', Recaptcha3Type::class, [
                'constraints' => new Recaptcha3(['message' => 'There were problems with your captcha. Please try again or contact with support and provide following code(s): {{ errorCodes }}']),
                'action_name' => 'contact',
                // 'script_nonce_csp' => $nonceCSP,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Contact::class,
        ]);
    }
}
```
contact.html.twig
```
    {{ form_start(form, {'attr': {'id': 'form-captcha'}}) }}
        {{ form_errors(form) }}
        {{ form_widget(form) }}
        <div class="text-center">
            <button class="btn btn-primary col-2">{{ button_label|default('Send') }}</button>
        </div>
    {{ form_end(form) }}
```

**Comment by karser** [comment]
1. The content of `Layout.html.twig` is not needed when you use Recaptcha3Type and the Symfony form.
2. Go through the [troubleshooting checklist](https://github.com/karser/KarserRecaptcha3Bundle#troubleshooting-checklist)

**Comment by Sheitak** [comment]
Okay ! Thank you,
I corrected this negligence,

Everything works well apparently, although my inspector always presents this famous error
`Error : Unknown base64 encoding at char :`
but I think that this does not prevent the operation, I was just trying to correct this problem,
If you have an idea do not hesitate, otherwise thank you to you and have a good day,

**Comment by karser** [comment]
I haven't encountered this error. Can you please locate the source of this error? At which particulate line it happens?

**Comment by Sheitak** [comment]
It's a bit fuzzy I admit, I'm sharing a screenshot for you to better understand the thing, I continue to do some research on my side
![base64](https://user-images.githubusercontent.com/34396292/95954595-d8c9fa80-0dfb-11eb-9661-8dbdf1c3e8e7.png)

**Comment by karser** [comment]
Thank you for the research @Sheitak ! Looks like this issue is related to ReCaptcha itself https://github.com/google/recaptcha/issues/392 . Closing this issue then.
