### ISSUE TITLE
Getting the score?

### ISSUE THREAD

**Issue by pbowyer** [karser/KarserRecaptcha3Bundle#36]
Thanks for writing this bundle, it's working flawlessly!

I would like to store the score with our form submissions, so I can verify that we've picked a good score_threshold.

I _thought_ that by mapping the form field I would get the details, but it returns a single long string.
```
->add('captcha', Recaptcha3Type::class, [
                'mapped' => true,
                'constraints' => new Recaptcha3(['message' => 'There were problems with your captcha. Please try again or contact with support and provide following code(s): {{ errorCodes }}']),
                'action_name' => 'manual',
            ])

# Gives
captcha = "03AGdBq27LZb9CZbMtrxPvl4JiscE5B...lots more...9I6j-5XzJS8"
```

Is it possible to retrieve the CAPTCHA check details?

**Comment by karser** [comment]
Can you please try [this PR](https://github.com/karser/KarserRecaptcha3Bundle/pull/38)?
use `composer require "karser/karser-recaptcha3-bundle:dev-recaptcha-get-score"` to test it.

Inject the Recaptcha3Validator and call getLastResponse()->getScore() after the form was submitted:
```
<?php

use Karser\Recaptcha3Bundle\Validator\Constraints\Recaptcha3Validator;

class TaskController extends AbstractController
{
    public function new(Request $request, Recaptcha3Validator $recaptcha3Validator): Response
    {
        //...
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            //...
            $score = $recaptcha3Validator->getLastResponse()->getScore();
            //...
        }
        //...
    }
}
```

**Comment by karser** [comment]
@pbowyer do you still need this?

**Comment by pbowyer** [comment]
Hi @karser yes we do, thanks - this works well for us.

**Comment by karser** [comment]
Great! I just merged and released it.
