### ISSUE TITLE
Captcha always invalid when form is sent multiple times with ajax

### ISSUE THREAD

**Issue by hdasdoria** [karser/KarserRecaptcha3Bundle#37]
Hello!

I'm having an issue while sending a form with a recaptcha input by ajax request.

My problem is:
- I send a form with an error (any invalid field)
- I re-render the form
- When I fix my invalid field and send the form again, it tells me the "Your computer or network may send invalid request"

My route used as form action is the Sylius [ResourceController:createAction](https://github.com/Sylius/SyliusResourceBundle/blob/master/src/Bundle/Controller/ResourceController.php#L171) and it renders a template with only the form

My javascript:
```javascript
import axios from 'axios'

export default () => {
    const container = document.querySelector('#contact-form')

    if (!container) return

    initForm(container)
}


const initForm = (container) => {
    const form = container.querySelector('form')

    if (!form) return

    form.addEventListener('submit', e => {
        e.stopPropagation()
        e.preventDefault()

        axios.post(form.action,
            new FormData(form),
            {
                headers: { 'Content-Type': 'multipart/form-data' }
            }
            ).then(({data}) => {
            container.innerHTML = data;
            initForm(container)
        })
    })
}
```

My form:
```php
class ContactRequestType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array                $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            // ...
            ->add('captcha', Recaptcha3Type::class, [
                'mapped'      => true,
                'constraints' => [
                    new Recaptcha3(),
                ],
            ]);
    }

    // ...
}
```

**Comment by karser** [comment]
You probably should call `recaptchaCallback_{{ validJsId }}` function after you receive the validation error. It'll obtain a new token from ReCaptcha. You should provide a new token each time the form is submitted. Take a look at [this function](https://github.com/karser/KarserRecaptcha3Bundle/blob/master/Resources/views/Form/karser_recaptcha3_widget.html.twig)

**Comment by hdasdoria** [comment]
Thanks, I will try this! Thought the fact I regenerate a new form each time would reset everything. Guess I was wrong about that.

**Comment by karser** [comment]
>Thought the fact I regenerate a new form each time would reset everything

Then make sure that the form is regenerated and each time the new token is submitted. Feel free to post the results here so we can continue the investigation.

When you are seeing "Your computer or network may send invalid request" most likely means you either submit the wrong token or the score is too low. Try enabling the detailed errors from the captcha's response:
```
$formBuilder->add('captcha', Recaptcha3Type::class, [
    'constraints' => new Recaptcha3(['message' => 'There were problems with your captcha. Please try again or contact with support and provide following code(s): {{ errorCodes }}']),
])
```

**Comment by hdasdoria** [comment]
Ok, so calling the `recaptchaCallback_{{ validJsId }}` after I get the response of every request solved my issue. I knew it was because my token was getting invalid cause of a new form, but forgot about this generated function!

Thanks for your help!

**Comment by hdasdoria** [comment]
For anyone wanting to do the same (sending through ajax and replacing the DOM with a new form) here is my modified JS:

```javascript
// ...
const initForm = (container) => {
    const form = container.querySelector('form')

    if (!form) return

    form.addEventListener('submit', e => {
        e.stopPropagation()
        e.preventDefault()

        axios.post(form.action,
            new FormData(form),
            {
                headers: { 'Content-Type': 'multipart/form-data' }
            }
            ).then(({data}) => {
            container.innerHTML = data;
            initForm(container)
            reloadRecaptcha()
        })
    })
}

const reloadRecaptcha = () => {
    document.querySelectorAll('input[name$="[captcha]"]')
        .forEach(inputEl => {
            const functionName = `recaptchaCallback_${inputEl.id}`

            if (window[functionName]) {
                window[functionName]()
            }
        })
}
```
