### ISSUE TITLE
The captcha value is missing

### ISSUE THREAD

**Issue by BarsikCat** [karser/KarserRecaptcha3Bundle#48]
Hello,

I'm continually getting "The captcha value is missing" message.

This is my first PHP project for more than a decade :)

The browser says that the form is successfully posted:

**Form data:**
```
contact_us[captcha]: 
03AGdBq26czW2_CFHbLvnvfy-qrzIYWMr1drr1WhcEyjJrElxSTHpG1MepvjeZF8Yafd2guBXZ9bbAMbSjdOJnli0RleE2f7rtht9-iRtKwxFqzn4tGn7ReDYesItAv8OvgbR7lF3Zw6o8IJG0QZlSL_aZrywQVfXUZ9TCsBYG0gDeW-X-ymG97XqgXbHX43bTe6oOmel5wNk94W2FTtiXgVxR0TLdG5QRnMVXPL06Cu6Y-TMEd5KH0hrADiSnZG7EZaTQSJNiVcDEB9WSX-rcnacgiHzkIgLVs9f6NrDpmS2lBpl1Lv6OCaYg0Jz1EFJx_fr2s_fP2vltuOWHOHojyWjdC30rJySUZ_35Yvslh4A8TmiNfGDn7bRlO2c990GVB9f5VINTa9yn1Zb6dAcZxDlFXrWg83Q5gV9wSL5y6ACALvrdi1IwvyqhDiK2TDydwxm741VMvttN
```

```
contact_us[_token]:
9af332ff29b1fead7c8a058.VhAT8CLqFjeAw7lsC2tQ_gKLAhNUODTRuizgDsU_HuA.LCMipHK4Z3i5p_obbj0XjDfUXVwGdXi76xuCfqZUf9MsPWCBRb9mR62FjQ
```

But debug details look strange for me:
![debug](https://user-images.githubusercontent.com/69058443/137223255-88ef5e4f-8bfd-43f7-8e75-44c3d75d3543.PNG)

I can share the entire project :)

**Comment by BarsikCat** [comment]
Invite sent. Complete newbie (in modern PHP) form processing realization made from current Symfony documentation.

**Comment by karser** [comment]
thank you, I'll take a look tomorrow

**Comment by BarsikCat** [comment]
Many thanks!
