### ISSUE TITLE
Doc: whitelisted dynamic link blocked

### ISSUE THREAD

**Issue by jmeyo** [karser/KarserRecaptcha3Bundle#71]
Seems your firebase dynamic link is not whitelisting

This is the first link of the main doc, wants to go to https://g.co/recaptcha/v3 

It also seems that firebase will be shutdown https://firebase.google.com/docs/dynamic-links/

**Comment by victorlazov** [comment]
IMO this should be replaced with this: https://www.google.com/recaptcha/admin/create

**Comment by karser** [comment]
fixed
