### ISSUE TITLE
 KarserRecaptcha3 VS Recaptcha3 Entreprise

### ISSUE THREAD

**Issue by radiz13** [karser/KarserRecaptcha3Bundle#78]
Hello,
I use recaptcha v3 enterprise, there is only one key (id). So, impossible to make the bundle work, certainly because of the missing second key.

RECAPTCHA3_KEY=RECAPTCHA_ID
RECAPTCHA3_SECRET=???

The captcha seems perfectly initialized :
`<input type="hidden" id="contact__token" name="contact[_token]" value="83e4.I82et384x0HxhHBwQ8p3oVJYMPoZC2LsiGlWpmQId-U.e4_00FJovhOHyygFBY8uxhwdZZhrek-Hww8n6V1GL4hNoKfTO3C2CqvKAw">`

But I have the form constraint error: karser_recaptcha3.message. I guess because of the RECAPTCHA3_SECRET ?

**Comment by karser** [comment]
Hello. I haven't tested this bundle with Recaptcha3 Entreprise but for the Standard version you should use key and secret when creating a new captcha:
![image](https://github.com/user-attachments/assets/834e80b3-40e0-4969-87f7-7360abe466e3)

**Comment by radiz13** [comment]
Yes, I know, there are 2 keys, but with enterprise there's only a key id (=RECAPTCHA3_KEY), no secret key

**Comment by radiz13** [comment]
Your bundle is ok with reCaptcha Enterprise. I had to recreate a new key, not from my Google Cloud this time (never had the secret key), but in deed from https://www.google.com/recaptcha which allowed me to obtain the secret key and associate with the Google cloud 🤪
Thx for that amazing bundle ❤️
