### ISSUE TITLE
Deprecated use of 'spaceless'

### ISSUE THREAD

**Issue by ehymel** [karser/KarserRecaptcha3Bundle#79]
Getting this in my logs after recent updates...

``Since twig/twig 3.12: Twig Filter "spaceless" is deprecated in /var/www/mysite/vendor/karser/karser-recaptcha3-bundle/Resources/views/Form/karser_recaptcha3_widget.html.twig at line 2.``

**Comment by karser** [comment]
should be fixed by [v0.1.28](https://github.com/karser/KarserRecaptcha3Bundle/releases/tag/v0.1.28), please check

**Comment by ehymel** [comment]
yes, that fixed it. Thank you.
