### ISSUE TITLE
JS error "Invalid side key"

### ISSUE THREAD

**Issue by mittererr** [karser/KarserRecaptcha3Bundle#9]
I have implemented KarserRecaptcha3Bundle to my project. In browser console I kepp on getting error: 

`Error: Invalid site key or not loaded in api.js: _reCAPTCHA_site_key_`

Site key was created in Google reCAPTCHA admin interface and copied to my configuration. Do you have any idea what goes wrong here?

**Comment by karser** [comment]
Have you setup recaptcha key/secret properly? Have you added the domain you use in the [recaptcha settings](https://www.google.com/recaptcha/admin)?


Can you confirm you are seeing this in the html of your rendered form?
```
<input type="hidden" id="form_captcha" name="form[captcha]" /><script>
    var recaptchaCallback_form_captcha = function() {
    grecaptcha.execute('<YOUR-RECAPTCHA-KEY>', {action: 'landing'}).then(function(token) {
    document.getElementById('form_captcha').value = token;
    });
    };
    </script><script src="https://www.google.com/recaptcha/api.js?render=<YOUR-RECAPTCHA-KEY>&onload=recaptchaCallback_form_captcha" async defer></script> 
</form>
```

**Comment by mittererr** [comment]
The setup at admin panel are correct - I have checked them again an again.

My code in rendered form is exactly:
```
<input type="hidden" id="contact_form_captcha" name="contact_form[captcha]" />
<script>
                var recaptchaCallback_contact_form_captcha = function() {
                    grecaptcha.execute('my_sitekey', {action: 'form'}).then(function(token) {
                        document.getElementById('contact_form_captcha').value = token;
                    });
                };
            </script>
<script src="https://www.google.com/recaptcha/api.js?render=my_sitekey&onload=recaptchaCallback_contact_form_captcha" async defer></script>
```

**Comment by karser** [comment]
This looks good. You should troubleshoot the google configuration.

>Have you added the domain you use in the [recaptcha settings](https://www.google.com/recaptcha/admin)?

Usually development domain differs from the production one, that's why I'm double asking this.

**Comment by mittererr** [comment]
I have added two domains "mydomain.at" and "mydomain.test" (for my test environment on MAMP). Both without www or something else. The error appears on both, test and live environment. 
I think there are not any more options which can be wrong?

**Comment by karser** [comment]
Yeah, there are very few options where you could make a mistake. Here is [the working example page](https://rc.trackmage.com/), which is running by this plugin, the code is the same, but the only difference is configuration and environment variables.
Try searching on [stackoverflow](https://stackoverflow.com/questions/48600034/recaptchaerror-for-site-owner-invalid-site-key) or posting a question there.

**Comment by mittererr** [comment]
Your site key looks different than mine. There are a couple of "-" in yours?

**Comment by karser** [comment]
Yep, make sure you created recaptcha of version 3.
![image](https://user-images.githubusercontent.com/1675033/71197591-9f3b6800-229a-11ea-8f1c-82985247420a.png)

**Comment by karser** [comment]
Yep, make sure you created recaptcha of version 3.
![image](https://user-images.githubusercontent.com/1675033/71197630-bbd7a000-229a-11ea-9421-7205d2e6f52c.png)

**Comment by mittererr** [comment]
Oh my god - after hours of debugging: There was another peace of code in my JS which causes the error. 
I think I'll have a beer now ;-)
Thank you!
